# Generated by Django 6.0 on 2025-12-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0010_remove_userprofile_signature_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF, DOCX, etc.)', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
