# Generated by Django 5.2.8 on 2026-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0011_add_resume_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecondition',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
